server:
  port: 8081

logging:
  level: debug

spring:
    freemarker:
        cache: false
        template-loader-path: classpath:/ftl/

    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/lenos?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
      encoding:
        force: true



mybatis:
    type-aliases-package: com.len.entity
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.len.base.BaseMapper
    not-empty: false
    identity: MYSQL


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql